version: '3.8'

services:
  db:
    image: postgres:16-alpine # Usa a imagem oficial do PostgreSQL (versão 16, versão slim Alpine)
    restart: always           # Garante que o container sempre reinicie
    environment:              # Variáveis de ambiente para o PostgreSQL
      POSTGRES_DB: metasfin.tech # Nome do banco de dados
      POSTGRES_USER: user        # Usuário do banco de dados
      POSTGRES_PASSWORD: admin123  # Senha do banco de dados
    ports:                    # Mapeia a porta do container para a sua máquina local
      - "5432:5432"           # Porta 5432 local para a porta 5432 do container
    volumes:                  # Mapeia um volume para persistência de dados
      - db_data:/var/lib/postgresql/data # Garante que os dados do banco não se percam ao reiniciar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d metasfin.tech"] # Verifica se o banco está pronto
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: # Define o volume para persistência dos dados